name: Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest
        run: npm run test
      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build the application
        run: npm run build
      - name: Start preview server and run tests
        run: |
          # Start the preview server with explicit host in the background
          npx vite preview --port 4173 --host 0.0.0.0 &
          SERVER_PID=$!
          
          # Give the server time to start
          echo "Waiting for server to start..."
          sleep 10
          
          # Run just a single test file first to identify issues
          echo "Running a single test file to identify potential issues"
          timeout 3m npx playwright test e2e/clip-type-validation.test.ts --project webkit --debug --trace on
          TEST_EXIT_CODE=$?
          
          # Kill the server process
          kill $SERVER_PID || true
          
          # Exit with the test exit code or timeout code
          if [ $TEST_EXIT_CODE -eq 124 ]; then
            echo "Tests timed out after 5 minutes"
            exit 1
          else
            exit $TEST_EXIT_CODE
          fi
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30